# Job titles containing any of these (case-insensitive) are considered relevant.
# Edit this list to change what gets scraped/emailed.
TARGET_KEYWORDS = [
    "Entry Level",
    "Junior",
    "Associate",
    "Graduate",
    "Automation",
    "Quality Assurance",
    "Cybersecurity",
    "Security Engineer",
    "Information Security",
    "Database",
    "SQL",
    "Cloud",
    "DevOps",
    "AWS",
    "Site Reliability",
    "Infrastructure",
    "Help Desk",
    "Technical Support",
    "Systems Administrator",
    "Network",
    "Desktop Support",
    "Software Engineer",
    "Software Developer",
    "Developer",
    "Programmer",
    "Full Stack",
    "Front End",
    "Back End",
    "Web Developer",
    "software",
    "data",
    "cad",
    "atc",
    "Analyst",
]
def is_relevant(title):
    # Substring match, not whole-word — e.g. "software" also matches "Software Engineer".
    return any(keyword.lower() in title.lower() for keyword in TARGET_KEYWORDS)