TARGET_KEYWORDS = [
    "Entry Level",
    "Junior",
    "Associate",
    "Graduate",
    "Automation",
    "QA",
    "Quality Assurance",
    "Cybersecurity",
    "Security Engineer",
    "Information Security",
    "Database",
    "SQL",
    "Cloud",
    "DevOps",
    "AWS",
    "Site Reliability",
    "Infrastructure",
    "IT",
    "Help Desk",
    "Technical Support",
    "Systems Administrator",
    "Network",
    "Desktop Support",
    "Software Engineer",
    "Software Developer",
    "Developer",
    "Programmer",
    "Full Stack",
    "Front End",
    "Back End",
    "Web Developer",
    "software",
]
def is_relevant(title):
    return any(keyword.lower() in title.lower() for keyword in TARGET_KEYWORDS)